### PR TITLE
Update README for argument of generate()

### PR DESCRIPTION
**Pull request by Kesin11**
Add more description of $num argument.

### CODE REVIEW

**Comment by yfuruyama** [comment]
Thanks for good pull request!
I noticed you modified `README.md` directly, but actually this file is auto-generated by pod description in module file.
cf.) https://github.com/tokuhirom/Minilla

So please modify pod description in `lib/Data/Generator/FromDDL.pm` file.

**Comment by Kesin11** [comment]
I move that description into pod.
Will `README.md` be fixed automatically? Should I use Minilla?

**Comment by yfuruyama** [comment]
No thanks. I will regenerate README.md by using your update.

**Comment by Kesin11** [comment]
I see. Thank you!

**Pull request merged**
